services:
  - type: web
    name: portfolio-flask
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: FLASK_ENV
        value: production
